### ISSUE TITLE
requiring booster vaccine at all times

### ISSUE THREAD

**Issue by fdamken** [pretix/pretix-covid-certificates#5]
We want to apply strict rules about who is allowed to enter our event and thus require a booster vaccination independent of whether a person was cured and/or tested. That's simply the following, right:
```python
{
    "or": [
        {"and": [{"var": "VACC"}, {"var": "VACC_isBooster"}]},
        {"var": "OTHER"},
    ]
},
```
If so, what does the `OTHER` option do? Is that for manual overwriting?

**Comment by raphaelm** [comment]
Honestly, it's been a year since anyone asked anything about this plugin, so I don't have the implementation details in my mind any more. The proposed rule could work, but it would need testing if it actually does the right thing in the app. The JSON logic was intended to be used to build rules for how to *combine* different certificate types, not how to *restrict* a single certificate type, so it might not work as intended, I'm not sure.

``OTHER`` is a joker type for certificates that are not a vaccination but should still be accepted after manual overrided (e.g. "doctor's note that vaccination is not possible")

**Comment by fdamken** [comment]
Hm, okay; then maybe we'll resort to manually checking the certificate using another app because we are under some time pressure and I don't have time for a long debug session.

Thanks for the fast response though!
